[package]
name = "minigrep"
version = "0.1.0"
authors = ["m5tfi <72708423+m5tfi@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
